# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Citrus and Toast
tagline:             'Eat your breakfast'
description:         'Citrus and Toast is a blog about the universe and everything in it'
url:                 http://citrusandtoast.com
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Citrus and Toast
  url:               https://twitter.com/
  email:             citrusandtoast@gmail.com

# Custom vars
version:             1.0.0
