# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lemons and Toast
tagline:             'Eat your breakfast'
description:         'Lemons and Toast is a blog about the universe and everything in it'
url:                 http://lemonsandtoast.com
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Lemons and Toast
  url:               https://twitter.com/
  email:             lemonsandtoast@gmail.com

# Custom vars
version:             1.0.0
